name: Docker Image CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:

  build:
    name: Flask

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./cloud_proj
        docker run --privileged -d docker:dind
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
